// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANco6VWp64RdbxRhJphT7mERCJVsc60l4',
    appId: '1:1053623085336:web:f86a951ccb1ceb8cb9166d',
    messagingSenderId: '1053623085336',
    projectId: 'wpflow-f0e71',
    authDomain: 'wpflow-f0e71.firebaseapp.com',
    storageBucket: 'wpflow-f0e71.firebasestorage.app',
    measurementId: 'G-0WT3HSRX8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6MyGWNjSc4o8cObVOpBnt2OM_piHWcFo',
    appId: '1:1053623085336:android:afd698f90bb7c542b9166d',
    messagingSenderId: '1053623085336',
    projectId: 'wpflow-f0e71',
    storageBucket: 'wpflow-f0e71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3vSwSqe3HE-pPGEu4qh8biHTp4ABEFRY',
    appId: '1:1053623085336:ios:3876ad5011c3379ab9166d',
    messagingSenderId: '1053623085336',
    projectId: 'wpflow-f0e71',
    storageBucket: 'wpflow-f0e71.firebasestorage.app',
    iosBundleId: 'com.example.wpflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3vSwSqe3HE-pPGEu4qh8biHTp4ABEFRY',
    appId: '1:1053623085336:ios:3876ad5011c3379ab9166d',
    messagingSenderId: '1053623085336',
    projectId: 'wpflow-f0e71',
    storageBucket: 'wpflow-f0e71.firebasestorage.app',
    iosBundleId: 'com.example.wpflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANco6VWp64RdbxRhJphT7mERCJVsc60l4',
    appId: '1:1053623085336:web:30cee60523cd0743b9166d',
    messagingSenderId: '1053623085336',
    projectId: 'wpflow-f0e71',
    authDomain: 'wpflow-f0e71.firebaseapp.com',
    storageBucket: 'wpflow-f0e71.firebasestorage.app',
    measurementId: 'G-T3PLLQHP8Q',
  );
}
